config/routes.rb
Rails.application.routes.draw do

  get 'categories/new'
  get 'categories/delete'
  get 'categories/index'
  resources :users
  resources :posts do
    member do
      post 'upvote'
    end
  end


  resources :sessions, only: [:new, :create, :destroy]

  root "posts#index"

  get "/about" => "about_us#show"

  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  get "submit", to: "posts#new", as: "submit"
  post "submit-post", to: "posts#create", as: "submit-post"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :description, length: {maximum: 140}, allow_blank: true
    validates :content, presence: true
    acts_as_votable
    has_one :category
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :user_nick, presence: true, uniqueness: true
  validates :password, presence: true, length: {:within => 8..20}
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
    def show
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    require "net/http"

    helper_method :current_user, :inspirational_quote

    def current_user
        if session[:user_id] and User.where(id: session[:user_id]).exists?
            @current_user ||= User.find(session[:user_id])
        else
            @current_user = nil
        end
    end

    # We just did this just to learn how to use files in ruby
    def inspirational_quote
        inspirational_quotes = File.new("app/assets/inspirational_quotes.txt", "r")
        number_of_quotes = File.read(inspirational_quotes).to_i
        selected_quote = rand(number_of_quotes)
        quote = IO.readlines(inspirational_quotes)[selected_quote]
        return quote
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
  end

  def delete
  end

  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    require "net/http"

    def index
        if params.has_key?(:category)
            @posts = Post.where(category_id: params['category'])
        else
            @posts = Post.all
        end
    end

    require 'net/http'
    require 'uri'

    def image_exists?(url)
        url = URI.parse(url_str)
        Net::HTTP.start(url.host, url.port) do |http|
            http.head(url.request_uri).code == '200'
        end
    rescue
        false
    end

    def create
        if current_user.nil?
            redirect_to root_path
        end

        @post = Post.new(post_params)
        @post.author = current_user.id
        @post.date = DateTime.now
        @post.community_votes = 0
        @post.annonymou_votes = 0
        
        if !image_exists?(@post.image)
            @post.image = nil
        end

        if @post.save
            redirect_to @post
        else
            render 'new'
        end
    end

    def new
        if current_user
            @post = Post.new
        else
            flash[:warning] = "You must be logged in to post"
            redirect_to root_path
        end
    end

    def show
        if !Post.exists?(params[:id])
            flash[:warning] = "Post was not found"
            redirect_to root_path
        else        
            @post = Post.find(params[:id])
        end
    end

    def upvote
        @post = Post.find(params[:id])
    end
        

    private

        def post_params
            params.require(:post).permit(:title, :content, :description, :image, :category_id)
        end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email_user_nick])
    if user.nil?
      user = User.find_by(user_nick: params[:email_user_nick])
    end
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Logged in"
      redirect_to root_url
    else
      flash.now[:warning] = "Nickname/email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    if !current_user || current_user[:admin] == false
      flash[:warning] = "Sneaky one, aren't ya?"
      redirect_to root_path
    else
      @users = User.all
    end
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.admin = false
    respond_to do |format|
      if @user.save
        flash[:success] = "Welcome abroad to Link Bay!"
        format.html { redirect_to root_path}
        format.json { render :show, status: :created, location: @user }
        session[:user_id] = @user.id
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Your account was updated' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Your account has been deleted' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name, :user_nick, :image)
    end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about_us/show.html.erb
<div class="container">
    <h1 class="text-dark text-center weight-bold mt-3">
        Welcome to link bay
    </h1>
    <h6 class="text-gray text-center mt-5">
        Imagine you wanted to learn something new, you would seach on google for the best book or videos or links to learn you new skill. 
    </h6>
    <h6 class="text-gray text-center mt-5">
        You would probably find many links, each of them suggesting a best course of action, each of them suggesting very different approaches about this.
    </h6>
    <h6 class="text-gray text-center mt-5">
        Suppose that you've tried many of these approaches and found that the first link's page and the fourth link's youtube tutorial were a good combination to learn what you wanted to understand. If you could share those two links, someone who wanted to learn the same as you would't have to scavange for the best resources like you did, if you could just find a way to tell them what you know.
    </h6>
    <h6 class="text-gray text-center mt-5">
        Suppose that you have to learn something fast, and you need the best resources without having to ask for someone's guidance, going out on the internet asking questions on forums nor take some shady link advice.
    </h6>
    <h6 class="text-gray text-center mt-5">
        Suppose that you want to find the best free content out there about a given topic, how can you determine what is best without having to go through all materials and rank them by yourself?
    </h6>
    <h6 class="text-gray text-center mt-5">
        Suppose that you wanted a community of learners, like you, that shares about their experiences of going out on the internet trying to understand new topics.
    </h6>
    <h5 class="text-gray text-center mt-5">
        We can help you with all of these.
    </h5>
    <h6 class="text-gray text-center mt-5">
        As the title suggests, our website has a simple intent: make learning easier, by matching people who know about diverse topics and let them put out their experiences. Everyone can vote on any post made and users rank what works best for them.
    </h6>
    <h6 class="text-gray text-center mt-5">
        Posts on this website have a single purpose: to link users with the best content out there for their needs.
    </h6>
    <div class="container text-center mb-3 mt-3">
        <a class="text-gray text-center mt-5 mb-5" href="/signup">
            Sign up!
        </a>
    </div>
    <div class="container text-center mb-4">
        <a href="/" class="">Home page</a>
    </div>
</div>

app/views/categories/delete.html.erb
<h1>Categories#delete</h1>
<p>Find me in app/views/categories/delete.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Link Bay</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="">
    <div class="page-container">

        <nav class="navbar navbar-expand-lg navbar-light color-dark-clean-blue" style="font-family:sans-serif">
            <a class="navbar-brand text-light font-weight-bold" href="/posts">LINK BAY</a>
            <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">

                <% if current_user %>
                    <li class="nav-item">
                        <a class="nav-link text-light" href="users/<%= current_user[:id] %>">Logged as: <%= current_user[:user_nick] %></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" href="/logout">Log out</a>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <a class="nav-link text-light" href="/login">Log in</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" href="/signup">Sign up</a>
                    </li>
                <% end %>
                <li class="nav-item">
                    <a class="font-color-light nav-link text-light" href="/posts/new">Create new tutorial</a>
                </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-light my-2 my-sm-0 text-light" type="submit">Search</button>
                </form>
            </div>
        </nav>

        <div class="container text-center mt-3">
            <% if flash[:warning] %>
                <div class="alert alert-danger" role="alert">
                    <%= flash[:warning] %>
                </div>
            <% elsif flash[:success] %>
                <div class="alert alert-success" role="alert">
                    <%= flash[:success] %>
                </div>
            <% end %>
        </div>
        
        <%= yield %>

    </div>
  </body>
</html>

app/views/posts/index.html.erb
<div class="container">

        <div class="dropdown text-center mt-3 mb-3">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
            </button>
                <div class="dropdown-menu dropdown-menu-center" aria-labelledby="dropdownMenuButton">
                <% Category.all.each do |category| %>
                    <a class="dropdown-item" href="?category=<%= category.id %>"><%= category.name %></a>
                <% end %>
            </div>
        </div>

        <% @posts.each do |post|  %>

            <div class="card mb-3">
                <div class="row no-gutters">

                    <% if !post.image.nil? %>                   
                        <div class="col-md-4">
                            <img src="<%= post.image %>" class="card-img" alt="...">
                        </div>
                    <% end %>

                    <div class="col-md-8">
                    <div class="card-body">
                        <a href="posts/<%= post.id %>" class="card-title"><%= post.title %>
                        </a>
                        <p class="card-text"><%= post.description %></p>
                        <p class="card-text"><small class="text-muted">3 meses</small></p>
                    </div>
                    </div>
                </div>
            </div>
    
        <% end %>

        <div class="container ">
            <ul class="pagination center">
                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
            </ul>
        </div>

</div>


<div class="container-fluid footer-navbar color-dark-clean-blue">
    <div class="row">
        <%= link_to "Learn more", "/about", class: "col text-left text-secondary" %>
        <small class="col text-secondary text-right col-10 d-sm-block d-none d-xl-block"><%= inspirational_quote %></small>
    </div>
</div>

app/views/posts/new.html.erb
<div class="container">
    <div class="block is-1 text-center">
        <h1 class="title is-size-1 center">Create a new post</h1>
    </div>
</div>


<div class="container text-center col-sm-8 mt-3">
    <%= bootstrap_form_for(@post) do |f| %>
        <%= f.text_field :title %>
        <%= f.text_field :description, label: 'Description'%>
        <%= f.text_area :content, :rows => "10", label: 'Body' %>
        <%= f.text_field :image %>
        <%= f.select :category_id, Category.all.collect { |p| [p.name, p.id] } %>
        <%= f.submit "Create new post", class: "btn btn-primary mb-3 mt-3" %>
    <% end %>
    
    <%= link_to 'Home', root_path %>
</div>

app/views/posts/show.html.erb
<div class="container text-center">
    <h1><%= @post.title %></h1>
    <h4 class="text-secondary mt-3">
        <%= @post.description %>
    </h4>
    <p class="mt-4">
        <%= @post.content %>
    </p>
</div>
<div class="container mt-5 row center">
    <%= button_to '+1' , method: :post %>
    
</div>
<div class="container text-center mt-5">
    
    <%= link_to 'Home', root_path %>
</div>

app/views/users/_form.html.erb
<div class="container">
  <%= simple_form_for(@user) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :email %>
      <%= f.input :password %>
      <%= f.input :name %>
      <%= f.input :user_nick %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container text-center col-sm-4">
    <h1 class="mb-4">Log in</h1>

    <%= bootstrap_form_for @user do |f| %>
        <%= f.text_field :name, label: 'Name' %>
        <%= f.text_field :email %>
        <%= f.text_field :user_nick, label: 'Nickname' %>
        <%= f.text_field :image, label: 'Image URL' %>
        <% if current_user.id == @user.id %>
            <%= f.password_field :password %>
        <% end %>
        <% if current_user and current_user.admin? %>
            <%= f.check_box :admin, label: 'Turn into admin' %>
            <br>
        <% end %>
        <%= f.submit "Update", class: "btn btn-primary mb-3 mt-3" %>
    <% end %>
    
    <%= link_to 'Home', root_path %>
</div>

app/views/users/index.html.erb
<div class="container text-center">
    <h3>Users</h3>
    <p><b>This is a admin-only, if you shouldn't be seeing this and is a good person, shoot us an email at renatomwbbritto@gmail.com</b></p>
    
    <div class="container w-75">
    <% @users.each do |user| %>
        <div class="row">
            <p class="w-25">
                <%= user.email %> / <%= user.user_nick %>
            </p>            <%= link_to 'User profile', user, class: "col" %>
            <%= link_to 'Edit user', edit_user_path(user), class: "col" %>
            <%= link_to 'Delete account', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "col"  %>
            <div class="divider"></div>
        </div>
    <% end %>
    </div>

    <br>

    <%= link_to 'Home', root_path %>
</div>

app/views/users/new.html.erb
<div class="container text-center col-sm-4">
    <h1 class="mb-4">Sign up</h1>

    <%= bootstrap_form_for(@user) do |f| %>
        <%= f.text_field :name %>
        <%= f.text_field :user_nick %>
        <%= f.email_field :email %>
        <%= f.text_field :image %>
        <%= f.password_field :password %>
        <%= f.password_field :password_confirmation %>
    <%= f.submit "Sign In", class: "mt-3 btn btn-primary mb-3"%>
    <% end %>
    
    <%= link_to 'Home', root_path %>
</div>

app/views/users/show.html.erb
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>